sudo: false

language: node_js

node_js:
  - node
  - "lts/*"
  - 10
  - 12
  - 14

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

notifications:
  email: false
